backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "posts"
    label: "Articoli"
    folder: "_posts"
    create: true
    slug: "{{year}}%%%{{month}}%%%{{day}}%%%{{slug}}RGMJ%%%"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Contenuto", name: "body", widget: "markdown"}
